DROP DATABASE IF EXISTS comp1006;
CREATE DATABASE comp1006;
USE comp1006;

CREATE TABLE pictures (
    picture_id				BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    picture_description		VARCHAR(100) NOT NULL,
    photo					VARCHAR(100) NOT NULL
);